export const BASIC_ELECTRICITY_TARIFF_NAME = "Basic electricity tariff";
export const BASIC_ELECTRICITY_TARIFF_MONTHLY_BASE_COST = 5;
export const BASIC_ELECTRICITY_TARIFF_MONTHLY_CONSUMPTION_COST_PER_KWH = 0.22;

export const PACKAGED_TARIFF_NAME = "Packaged tariff";
export const PACKAGED_TARIFF_BASE_KWH = 4000;
export const PACKAGED_TARIFF_BASE_TARIFF = 800;
export const PACKAGED_TARIFF_COST_PER_KWH_ABOVE_BASE_KWH = 0.3;